### ISSUE TITLE
#382 Old permissions in handlerCan mapping are still attached to the safeHandler of a transferred safe

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#219]
> # Lines of code
> https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L136 https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L41
> 
> # Vulnerability details
> ## Impact
> A safe is associated with a unique safeHandler. This safeHandler can give permissions to addresses through the [allowHandler()](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L112) function which stores these approvals/disapprovals in the [handlerCan](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L41) mapping. Now let's say there is a safeHandler which has permissioned some addresses in the handlerCan mapping. When this safe is transferred to a new owner, the previous permissions that were added to the safeHandler are still attached to it without the new owner realizing it.
> 
> ## Proof of Concept
> Here is the whole process:
> 
> https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L112C1-L115C4
> 
> 1. Safe handler of a safe (owned by owner A) approves addresses [X,Y,Z] to the [handlerCan](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L41) mapping through the [allowHandler() function](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L112C1-L115C4).
> 
> ```solidity
> File: ODSafeManager.sol
> 112:   function allowHandler(address _usr, uint256 _ok) external {
> 113:     handlerCan[msg.sender][_usr] = _ok;
> 114:     emit AllowHandler(msg.sender, _usr, _ok);
> 115:   }
> ```
> 
> 2. Owner A now transfers the safe (associated with the safe handler) to an Owner B through the [safeTransferFrom() function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7c8b7a27284f503ce8ae23d63ac9403096dcf6fe/contracts/token/ERC721/ERC721.sol#L152) in the Vault721.sol contract which [inherits the ERC721Enumerable contract](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/Vault721.sol#L13) (that inherits the ERC721 contract). During the call, the [_afterTokenTransfer()](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/Vault721.sol#L187) hook is called ([overridden in the Vault721.sol contract](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/Vault721.sol#L187)), which further calls the [transferSAFEOwnership() function](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L136C1-L152C4). In the function, we can see that the safe is transferred but the [handlerCan](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L41) mapping is not updated for the safeHandler, which means the old permissions (addresses [X,Y,Z]) for the safeHandler are still attached without the new owner B realizing it.
> 
> ```solidity
> File: ODSafeManager.sol
> 136:   function transferSAFEOwnership(uint256 _safe, address _dst) external {
> 137:     require(msg.sender == address(vault721), 'SafeMngr: Only Vault721');
> 138: 
> 139: 
> 140:     if (_dst == address(0)) revert ZeroAddress();
> 141:     SAFEData memory _sData = _safeData[_safe];
> 142:     if (_dst == _sData.owner) revert AlreadySafeOwner();
> 143: 
> 144: 
> 145:     _usrSafes[_sData.owner].remove(_safe);
> 146:     _usrSafesPerCollat[_sData.owner][_sData.collateralType].remove(_safe);
> 147: 
> 148: 
> 149:     _usrSafes[_dst].add(_safe);
> 150:     _usrSafesPerCollat[_dst][_sData.collateralType].add(_safe);
> 151: 
> 152:
> 153:     _safeData[_safe].owner = _dst;
> 154: 
> 155: 
> 156:     emit TransferSAFEOwnership(msg.sender, _safe, _dst);
> 157:   }
> ```
> 
> ## Tools Used
> Manual Review
> 
> ## Recommended Mitigation Steps
> It is not possible to remove the [handlerCan](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L41) permissions in the [transferSAFEOwnership() function](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L136C1-L152C4) since it is stored in a mapping. The only solution to this would be to add another key field (named _owner) to update the safeHandler permissions correctly whenever a safe is transferred. We can see this pattern implemented for the [safeCan mapping](https://github.com/open-dollar/od-contracts/blob/f4f0246bb26277249c1d5afe6201d4d9096e52e6/src/contracts/proxies/ODSafeManager.sol#L39), which correctly updates the safe permissions on transfer.
> 
> Solution (use this mapping instead):
> 
> ```solidity
> File: ODSafeManager.sol
> 41:   mapping(address _owner => (address _safeHandler => mapping(address _caller => uint256 _ok))) public handlerCan;
> ```
> 
> ## Assessed type
> Error

**Comment by 0xdavinchee** [comment]
gm! 

## High-level Overview

The finding here illustrates how the `handlerCan` mapping has an issue where if you called `allowHandler` previously and then transferred your safe, the handlerCan approvals would still apply and the approved addresses would be able to call `enterSystem` and `exitSystem` on behalf of the new owner.

> Note that the recommended fix doesn't resolve the issue found in #217 in the sense that it doesn't fully remove/clear the permissions even with the addition of the `address _owner` to top level of the `handlerCan` mapping.

## Proposed Fix

I think the proposed fix makes sense, however, we likely will want to add a nonce to it similar to the #217 fix at some point. Note: 
- `the "handler" can be the SafeHandler, the Proxy, or even the user's EOA`
- there is no discoverability in terms of finding who the owner is given a "handler" currently
  - One solution is creating a new mapping (`mapping (address _handler => address _owner) internal _handlerOwners`) and updating it in `openSAFE` from the handler to the owner of the safe
- adding an `_owner` to the top level of the mapping would require us to change a few places in the code which `handlerCan` is used, namely, the `handlerAllowed` modifier and `allowHandler` function
  - These functions would require discoverability of finding the owner
    - In the `handlerAllowed` modifier, we could pass the `_safe` id parameter and get the `SAFEData` of the safe and thus get the owner of the safe
    - The behavior of `allowHandler` would likely need to be redefined as the function isn't permissioned, we would likely only want to allow the handler to set permissions for the current owner as retrieved from `_handlerOwners` (the assumption here is that each handler only has one owner).

## TODOs

- [ ] Modify the `handlerCan` mapping to include `address _owner` at the top level
- [ ] Add a new `_handlerOwners` mapping
- [ ] Alter the `handlerAllowed` to take `uint256 _safe` in addition to the address it is currently taking
- [ ] Redefine the expected behavior and limits of the `allowHandler` function and implement those changes

**Comment by 0xdavinchee** [comment]
enterSystem and quitSystem might not be required for the protocol to function and so this issue can be closed

**Comment by pi0neerpat** [comment]
> enterSystem and quitSystem might not be required for the protocol to function and so this issue can be closed

I'm open to this idea. We would remove these functions completely? Are there any additional changes needed to close this issue?

**Comment by 0xdavinchee** [comment]
> I'm open to this idea. We would remove these functions completely? Are there any additional changes needed to close this issue?

If we deem these functions unnecessary then we would remove the functions, the associated mapping variable: `handlerCan`, the modifier: `handlerAllowed` and the custom error: `HandlerNotAllowed`.

**Comment by 0xdavinchee** [comment]
currently blocked by #277
